pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                // Show Maven version
                sh 'mvn --version'
                
                // Run Maven commands to clean, install, and package the Java project
                sh 'mvn clean install package'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                // Show Node.js version
                sh 'node --version'
                
                // Install npm dependencies
                sh 'npm install'
                
                // Run the Node.js application
                sh 'npm run start'
            }
        }
    }
}
