pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3.8.1-adoptopenjdk-11' }
            }
            steps {
                // Show Maven version
                sh 'mvn --version'
                
                // Create pom.xml file for Maven
                writeFile file: 'pom.xml', text: '''
                <project xmlns="http://maven.apache.org/POM/4.0.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
                    <modelVersion>4.0.0</modelVersion>
                    <groupId>com.example</groupId>
                    <artifactId>backend</artifactId>
                    <version>1.0-SNAPSHOT</version>
                    <build>
                        <plugins>
                            <plugin>
                                <groupId>org.apache.maven.plugins</groupId>
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.8.1</version>
                                <configuration>
                                    <source>11</source>
                                    <target>11</target>
                                </configuration>
                            </plugin>
                        </plugins>
                    </build>
                </project>
                '''
                
                // Run Maven commands
                sh 'mvn clean install package'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:16-alpine' }
            }
            steps {
                // Show Node.js version
                sh 'node --version'
                
                // Create package.json file for npm
                writeFile file: 'package.json', text: '''
                {
                    "name": "frontend",
                    "version": "1.0.0",
                    "description": "Hello World Node.js Application",
                    "main": "frontend.js",
                    "scripts": {
                        "start": "node frontend.js"
                    },
                    "author": "",
                    "license": "ISC",
                    "dependencies": {}
                }
                '''
                
                // Run npm commands
                sh 'npm install'
                sh 'npm run start'
            }
        }
    }
}

